import compose from 'koa-compose';
import includes from 'lodash/collection/includes';
import intersection from 'lodash/array/intersection';
import keysIn from 'lodash/object/keysIn';
import route from 'koa-route';

const URL_WITH_NAME = name => `/${name}`;
const URL_WITH_PARAM = name => `/${name}/${name}Param`;
const URL_WITH_NEW = name => `/${name}/new`;
const URL_WITH_EDIT = name => `/${name}/edit`;

// Constant containing our actions
const ACTIONS = {
  'index': {
    method: 'get',
    url: URL_WITH_NAME,
    similar: ['create'],
  },
  'show': {
    method: 'get',
    url: URL_WITH_PARAM,
    similar: ['update', 'destroy'],
  },
  'create': {
    method: 'post',
    url: URL_WITH_NAME,
    similar: ['index'],
  },
  'new': {
    method: 'get',
    url: URL_WITH_NEW,
    similar: [],
  },
  'edit': {
    method: 'get',
    url: URL_WITH_EDIT,
    similar: [],
  },
  'update': {
    method: 'put',
    url: URL_WITH_PARAM,
    similar: ['show', 'destroy'],
  },
  'destroy': {
    method: 'delete',
    url: URL_WITH_PARAM,
    similar: ['show', 'update'],
  },
};

/**
 * A simple middleware that responds to disallowed methods with a 405 response.
 *
 * @param {Array.<String>} actionList List of implemented actions
 * @param {Array.<String>} similarActions List of relevant actions
 *
 * @return {GeneratorFunction}
 */
function methodNotAllowed(actionList, similarActions) {
  const methods = intersection(actionList, similarActions).map(
    action => ACTIONS[action].method.toUpperCase()
  );

  return function* middleware(next) {
    this.status = 405;
    this.set('Allow', methods.join(','));
    yield* next;
  };
}

/**
 * A recursive generator function that yields koa-route middlewares for each route.
 *
 * @param {Object} resources Contains all resources and their actions.
 * @param {String} prefix String to prepend to URL when generating routes.
 * @param {String} resourceName Name of the current resource we are processing.
 *
 * @return {Iterable}
 */
function* getMiddlewares(resources, prefix = '', resourceName = '') {
  // If our resources object is null, return
  if (resources === null || typeof resources !== 'object') return;

  // Extract resource keys, and remove any key that starts in an underscore
  const resourceKeys = keysIn(resources).filter(key => key[0] !== '_');

  // Determine if this object has actions as properties
  const actionList = intersection(resourceKeys, keysIn(ACTIONS));
  const hasActions = actionList.length > 0;

  // Iterate through each action if we have at least one action
  if (hasActions) {
    // Check for invariant violations
    if (resourceName === '') {
      throw Error('The root resource object cannot contain actions.');
    }

    for (const name in ACTIONS) {
      // Check for invariant violations
      if (typeof resources[name] !== 'undefined' && typeof resources[name] !== 'function') {
        throw Error(`Action '${name}' must be a function.`);
      }

      const action = ACTIONS[name];
      yield route[action.method](
        `${prefix}${action.url(resourceName)}`,
        resources[name] || methodNotAllowed(actionList, action.similar)
      );
    }
  }

  // Iterate through the rest of the methods (non-actions)
  for (let index = 0; index < resourceKeys.length; index++) {
    const key = resourceKeys[index];
    if (!includes(keysIn(ACTIONS), key)) {
      let innerPrefix;

      // Determine prefix to send to inner resource
      if (resourceName === '') {
        innerPrefix = prefix;
      } else if (hasActions) {
        innerPrefix = `${prefix}/${resourceName}/:${resourceName}Param`;
      } else {
        innerPrefix = `${prefix}/${resourceName}`;
      }

      // Iterate through inner resources
      yield* getMiddlewares(resources[key], innerPrefix, key);
    }
  }
}

/**
 * Creates the middleware given resources and their actions.
 *
 * @param {Object} resources Contains all resources and their actions.
 *
 * @return {GeneratorFunction} The middleware.
 */
export default function resourceRoutes(resources) {
  // Use koa-compose on all REST middlewares generated by getMiddlewares
  return compose(Array.from(getMiddlewares(resources)));
}
